"""Add responsible person model

Revision ID: 62f288a99201
Revises: a35f8a4bbfc9
Create Date: 2026-05-12 20:51:31.540233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '62f288a99201'
down_revision: Union[str, Sequence[str], None] = 'a35f8a4bbfc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('responsible_persons',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('monitoring_task_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['monitoring_task_id'], ['monitoring_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('monitoring_tasks', 'notification_emails')
    op.drop_column('monitoring_tasks', 'responsible_persons')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitoring_tasks', sa.Column('responsible_persons', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.add_column('monitoring_tasks', sa.Column('notification_emails', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.drop_table('responsible_persons')
    # ### end Alembic commands ###
