"""Add monitoring task fields

Revision ID: a35f8a4bbfc9
Revises: ca933d1c249d
Create Date: 2026-05-10 15:19:02.346566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a35f8a4bbfc9'
down_revision: Union[str, Sequence[str], None] = 'ca933d1c249d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitoring_tasks', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('monitoring_tasks', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('monitoring_tasks', sa.Column('url', sa.String(length=2048), nullable=False))
    op.add_column('monitoring_tasks', sa.Column('http_method', sa.String(length=10), nullable=False))
    op.add_column('monitoring_tasks', sa.Column('headers', sa.JSON(), nullable=True))
    op.add_column('monitoring_tasks', sa.Column('timeout', sa.Integer(), nullable=False))
    op.add_column('monitoring_tasks', sa.Column('expected_status_code', sa.Integer(), nullable=False))
    op.add_column('monitoring_tasks', sa.Column('sla_target', sa.Float(), nullable=False))
    op.add_column('monitoring_tasks', sa.Column('check_interval_seconds', sa.Integer(), nullable=False))
    op.add_column('monitoring_tasks', sa.Column('cron_expression', sa.String(length=255), nullable=True))
    op.add_column('monitoring_tasks', sa.Column('responsible_persons', postgresql.ARRAY(sa.String()), nullable=False))
    op.add_column('monitoring_tasks', sa.Column('notification_emails', postgresql.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitoring_tasks', 'notification_emails')
    op.drop_column('monitoring_tasks', 'responsible_persons')
    op.drop_column('monitoring_tasks', 'cron_expression')
    op.drop_column('monitoring_tasks', 'check_interval_seconds')
    op.drop_column('monitoring_tasks', 'sla_target')
    op.drop_column('monitoring_tasks', 'expected_status_code')
    op.drop_column('monitoring_tasks', 'timeout')
    op.drop_column('monitoring_tasks', 'headers')
    op.drop_column('monitoring_tasks', 'http_method')
    op.drop_column('monitoring_tasks', 'url')
    op.drop_column('monitoring_tasks', 'is_active')
    op.drop_column('monitoring_tasks', 'description')
    # ### end Alembic commands ###
