"""Add body field to monitoring task model

Revision ID: b1ea2a2ef425
Revises: 884b3b52a7b7
Create Date: 2026-05-15 19:29:40.506162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1ea2a2ef425'
down_revision: Union[str, Sequence[str], None] = '884b3b52a7b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_metrics_task_id'), table_name='daily_metrics')
    op.create_index(op.f('ix_daily_metrics_monitoring_task_id'), 'daily_metrics', ['monitoring_task_id'], unique=False)
    op.drop_index(op.f('ix_incidents_task_id'), table_name='incidents')
    op.add_column('monitoring_tasks', sa.Column('body', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitoring_tasks', 'body')
    op.create_index(op.f('ix_incidents_task_id'), 'incidents', ['monitoring_task_id'], unique=False)
    op.drop_index(op.f('ix_daily_metrics_monitoring_task_id'), table_name='daily_metrics')
    op.create_index(op.f('ix_daily_metrics_task_id'), 'daily_metrics', ['monitoring_task_id'], unique=False)
    # ### end Alembic commands ###
